@startuml Пример C4: Контекст
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title  Медицинская система записи - Контекстная диаграмма

Person(пациент,"Пациент","Записывается на приём к врачу, просмотраривает историю приёмов, пишет отзывы")
Person(врач, "Заказчик", "Просмотр расписания, ввод данных приёма пациента" )
Person(административный_персонал,"Административный персонал","управляет расписанием врачей, анализ загрузки")
Person(системный_администратор,"Системный администратор","Настройка, безопасность, резервное копирование")

System(медицинская_система,"Медицинская система записи","Обеспечивает запись на приём к врачам, управление расписанием и хранение данных пациентов")

System_Ext(система_резервного_копирования,"Система резервного копирования","Внешняя служба резервного копирования данных")
System_Ext(внешняя_лис,"Внешняя ЛИС","Внешняя медицинская информационная система")
System_Ext(внешняя_мис,"Внешняя МИС","Внешняя лабораторно-информационная система")
System_Ext(система_уведомлений,"Система уведомлений (SMS/email)","Внешняя служба отправки уведомлений пациентам и персоналу")

Rel(пациент,медицинская_система,"Записывается на приём, просматривает историю записей на приём, пишет отзывы о приёмах и врачах","HTTPS")
Rel(врач,медицинская_система,"Просмотривает своё расписание, вводит данных приёма пациента","HTTPS")
Rel(административный_персонал,медицинская_система,"Управляет расписанием врачей, аналазирует нагрузку на врачей и отзывы","HTTPS")
Rel(системный_администратор,медицинская_система,"Настраивает систему, обеспечивает безопасность, настраивает резервное копирование","HTTPS")

Rel(медицинская_система,внешняя_мис,"Расписание, справочники(МКБ-10), импорт/экспорт данных","API/HTTPS")
Rel(медицинская_система,внешняя_лис,"Результаты исследований","API/HTTPS")
Rel(медицинская_система,система_уведомлений,"Отправка напоминаний о приеме, изменениях, готовности результатов ( Email, SMS, push )","API/HTTPS")
Rel(медицинская_система,система_резервного_копирования,"Плановое сохранение полных/инкрементальных бэкапов","API/HTTPS")

@enduml
